n1 = int(input("Enter the first value\n"))
n2 = int(input("Enter the second value\n"))
print(n1, "+", n2, "=", n1+n2)
print(n1, "-", n2, "=", n1-n2)
print(n1, "x", n2, "=", n1*n2)
print(n1, "/", n2, "=", n1/n2)
