print("---Jhoony Jhoony Yes Papa--")
print("Papa  : Jhoony Jhonny")
print("Jhoony: Yes Papa")
print("Papa  : Eating Sugur")
print("Jhoony: No Papa")
print("Papa  : Telling your lies")
print("Jhoony: No Papa")
print("Papa  : Open your mouth")
print("Jhoony: Hahahahaha!")
